Azjol nerub a little fix
Zidras/DBM-Warmane pull request #105
Opened 2022-01-25 01:16 UTC by Nispodzianka

azjol with this fix
1st boss: https://youtu.be/hLGskpfwB7k?t=122
2nd boss: https://youtu.be/hLGskpfwB7k?t=422

2022-01-31 00:12 UTC, Zidras requested changes

2022-01-31 00:12 UTC, Zidras commented on DBM-Party-WotLK/AzjolNerub/Hadronox.lua
> +local specWarningCloud	= mod:NewSpecialWarningMove(53400, nil, nil, nil, 1, 2)
`NewSpecialWarningGTFO` seems more adequate for this

2022-01-31 00:12 UTC, Zidras commented on DBM-Party-WotLK/AzjolNerub/Hadronox.lua
> +	"SPELL_PERIODIC_DAMAGE 53400 59419"
missing `"SPELL_PERIODIC_MISSED 53400 59419"`

2022-01-31 00:12 UTC, Zidras commented on DBM-Party-WotLK/AzjolNerub/Hadronox.lua
> +end
missing `mod.SPELL_PERIODIC_MISSED = mod.SPELL_PERIODIC_DAMAGE`

2022-01-31 00:12 UTC, Zidras commented on DBM-Party-WotLK/AzjolNerub/Krikthir.lua
> +		if args:IsPlayer() then
warning should pick up everything (maybe disabled by default, but it shouldn't be restricted to player only).
if only player matter, perhaps a new specWarn is better?

2022-01-31 01:15 UTC, Nispodzianka commented on DBM-Party-WotLK/AzjolNerub/Krikthir.lua
> +		if args:IsPlayer() then
without `if args:IsPlayer() then` we see warningCurse:Show() everytime any person in PT get this debuff soo if 4 ppl get curse we have spam and we see 3x warningCurse - I dont think this debuff its so important that we need this spam

2022-02-01 19:14 UTC, Zidras commented on DBM-Party-WotLK/AzjolNerub/Krikthir.lua
> +		if args:IsPlayer() then
Usually, DBM mod follows this logic:
specWarn for player
warn for others

I don't agree with removing options. My suggestion is:
```lua
		if args:IsPlayer() then
		  specWarnCurse:Show()
	    else
      warningCurse:Show()
end      
```
and warnCurse disabled in the mod default option

2022-02-02 00:44 UTC, Zidras approved these changes

2022-02-02 00:47 UTC, merged