ICC_LK Infest counter add
Zidras/DBM-Warmane pull request #57
Opened 2021-10-05 22:47 UTC by Nispodzianka

2021-10-05 22:50 UTC, Zidras requested changes

2021-10-05 22:50 UTC, Zidras commented on DBM-Icecrown/TheFrozenThrone/LichKing.lua
> +local warnInfest			= mod:NewCountAnnounce(73779, 3, nil, "Healer|RaidCooldown") --Phase 1 & 2 Ability
I won't change default constructors. For me to consider this, it needs to be an option to add count

2021-10-05 22:50 UTC, Zidras commented on DBM-Icecrown/TheFrozenThrone/LichKing.lua
> +local timerInfestCD			= mod:NewNextCountTimer(22.5, 70541, nil, "Healer|RaidCooldown", nil, 5, nil, DBM_CORE_L.HEALER_ICON, nil, nil, 4)
same

2021-10-06 00:19 UTC, Nispodzianka commented
check if this is what you mean, I added a new warning and timer for Infest setting them as hidden by default - because I guess you don't want these new options to be ON by default and the old ones to be hidden ;)

2021-11-20 22:15 UTC, closed without merging